version: '3.5'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:

# services:
#   crdb:
# #    image: christoofar/cockroachdb-arm64:latest
#     image: cockroachdb/cockroach:latest
#     ports:
#       - "26257:26257"
#       - "8080:8080"
#     command: start-single-node --insecure
#     environment:
#       # COCKROACH_PASSWORD: corkroach
#       COCKROACH_USER: corkroach
#       COCKROACH_DATABASE: corkroach
#     # platform: linux/arm64
#     volumes:
#       - "cockroach-data:/cockroach/cockroach-data"
#     restart: unless-stopped
# volumes:
#   cockroach-data:

